#!/bin/sh
set -e
if [ "$1" = configure ]; then
    install -d -m 0755 /var/lib/sonic-guardian /etc/sonic/guardian
    python3 /usr/share/sonic-guardian/install-plugins.py
    python3 /usr/share/sonic-guardian/install-yang.py
    if [ -d /run/systemd/system ]; then
        systemctl daemon-reload
    fi
fi
#DEBHELPER#
